### ISSUE TITLE
Using 'zinnia.plugins.placeholder.EntryPlaceholder' as Entry Base Model causes DatabaseError

### ISSUE THREAD

**Issue by chrislawlor** [Fantomas42/django-blog-zinnia#107]
When using ''zinnia.plugins.placeholder.EntryPlaceholder', as ZINNIA_ENTRY_BASE_MODEL as suggested [in the configuration docs](http://django-blog-zinnia.com/documentation/configuration/#django-cms), a DatabaseError is generated when visiting http://localhost:8000/admin/zinnia/. (0.8.1 release).

Examination reveals that the column zinnia_entry.content_placeholder_id does not get created by either the `syncdb` or `migrate` commands.

Creating the column manually (`ALTER TABLE zinnia_entry ADD COLUMN content_placeholder_id integer` on PostgreSQL) is an interim fix.

**Comment by bittner** [comment]
I believe this is being referred to in the [installation instruction of cmsplugin-zinnia](https://github.com/django-blog-zinnia/cmsplugin-zinnia/blob/develop/README.rst#entries-with-plugins). Though, with Django 1.8+ the mentioned instruction do not directly help, and are merely a hint on how to fix the issue. A complete solution in the README would be nice.

**Comment by bittner** [comment]
As explained in the [Zinnia docs](http://docs.django-blog-zinnia.com/en/latest/how-to/extending_entry_model.html#considerations-about-the-database) with Django 1.7+ we can use the `MIGRATION_MODULES` settings to provide a full set of migrations properly inside our own projects. You can go about it like this:

You have this in your project settings already:
``` python
ZINNIA_ENTRY_BASE_MODEL = 'cmsplugin_zinnia.placeholder.EntryPlaceholder'
```
Now run `python manage.py migrate`, and afterwards `python manage.py makemigrations`.

This will create an additional migration `0003_entry_content_placeholder.py` in the migrations folder of zinnia (i.e. the zinnia package in the site-packages of your virtual environment). You can copy all migrations of Zinnia including the new one to a migrations folder in your project, e.g. `myproject/migrations/zinnia/`.

Now, add this to your project settings:
``` python
MIGRATION_MODULES = {
    'zinnia': 'myproject.migrations.zinnia',
    # (you may have other migrations here already for django CMS 3 plugins)
}
```
(Note that the Zinnia documentation suggests to collapse all prior migrations into an initial migration. However, when you do it this way your migrations fully match Zinnia's migration, which may be good for retracing changes for historical and debugging reasons one day.)

Your project migrations will have a Zinnia folder like this:
```
myproject/migrations/
├── __init__.py
└── zinnia
    ├── __init__.py
    ├── 0001_initial.py
    ├── 0002_lead_paragraph_and_image_caption.py
    └── 0003_entry_content_placeholder.py
```
Now everything is in place in your project, and you can run `python manage.py migrate`. Zinnia will work with django CMS' placeholders, and you can re-execute those migrations again from zero anytime.
