### ISSUE TITLE
New install on django-cms breaks site

### ISSUE THREAD

**Issue by crooksey** [Fantomas42/django-blog-zinnia#115]
I have installed zinnia as per the docs and the same way I always have done.

I have synced and migrated my database and on standard pages not related to the blog, I get the error:

"Caught DatabaseError while rendering: relation "zinnia_entry" does not exist LINE 1: ...te", "zinnia_entry"."content_placeholder_id" FROM "zinnia_en... ^"

That relates to the "{% show_menu 0 100 100 100 %}" section of my templates.

Now on the page where zinnia is aphooked, I get the error

relation "zinnia_entry" does not exist
LINE 1: SELECT COUNT(*) FROM "zinnia_entry" INNER JOIN "zinnia_entry...

Using postgresql + south

**Comment by bittner** [comment]
See [issue #107](https://github.com/Fantomas42/django-blog-zinnia/issues/107#issuecomment-141711838) for a description on how to go about this with Django 1.7 and 1.8+.

The migration for the placeholder [looks like this](https://github.com/Organice/django-organice/blob/master/organice/migrations/zinnia/0003_entry_content_placeholder.py).
