### ISSUE TITLE
Translation strings for different sentence syntax

### ISSUE THREAD

**Issue by aladagemre** [Fantomas42/django-blog-zinnia#159]
Hi,

I was translating your app to Turkish but there are some problems with the translation mechanism due to differences in preposition syntax.

For example:
There exists a string:

RSS Feed of pingbacks on

Possibly you should have used {% trans "RSS Feed of pingbacks on" %} {{variable}} ...

But Turkish sentences with such preposition (on) uses syntax:
{{variable}} on RSS Feed pingbacks

So I can't translate this sentence. If you could use
{% blocktrans %}RSS Feed of pingbacks on {{variable}}{%endblocktrans%}

Then I could translate it into:
{{variable}} on RSS Feed pingbacks
{{variable}} üzerinde RSS Besleme geri bağlantıları

The problematic words that are prepositions: of, to, in, from, with, without, about, against, among, at, before, after, etc...

http://en.wikibooks.org/wiki/Turkish/Cases

I know that it'd be problematic to fix them all but I may give it a try and you could keep this problem in mind for further translation tags.

**Comment by Fantomas42** [comment]
Current list of problematic translation strings:

https://gist.github.com/Fantomas42/436dba18b7f874a0bfb8

**Comment by bittner** [comment]
I have the same issue with German (see my comment on [_recent_linkbacks.html](https://github.com/Fantomas42/django-blog-zinnia/commit/960d0a821a454156659ce67f8b2896e8ed371b52) for example).

Text segments (for translation) should ideally be complete, atomic units: full sentences, full headers, etc. This gives much of the needed flexibility for translation. Probably `blocktrans` is better suited than `trans` for this job in the templates.

BTW, self-explanatory placeholders (e.g. `%(linkbacks_per_entry)s ...`) in the text segments are awesome and help a lot with translation. That's nice to see in your source code!

**Comment by Fantomas42** [comment]
@bittner any improvement on this issue is welcome. Especially from a German speaker :)

**Comment by Fantomas42** [comment]
Like described in https://gist.github.com/Fantomas42/436dba18b7f874a0bfb8 three sentences cause a problem.

These 3 sentences are related to the same block in the same template. The block is too complex too handle a correct internationalization, it contains blocks, conditions, and loops.

So I close the issue.
