### ISSUE TITLE
'Cannot resolve keyword 'entries' into field. Choices are: comment_comments...' 

### ISSUE THREAD

**Issue by ckcollab** [Fantomas42/django-blog-zinnia#172]
Hey gang,

I'm not quite sure why I'm getting this error, but I'm going here:

```
http://127.0.0.1:8000/admin/zinnia/entry/
```

And getting this:

```
FieldError at /admin/zinnia/entry/
Cannot resolve keyword 'entries' into field. Choices are: comment_comments, comment_flags, date_joined, email, first_name, forum, forumreadtracker, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, poll_answers, posts, pybb_profile, readed_forums, readed_topics, registrationprofile, subscriptions, topic, topicreadtracker, user_permissions, username, userprofile
```

But this page works:

```
http://127.0.0.1:8000/admin/zinnia/category/
```

I did syncdb --migrate; it all seems to be up to date!  I'm using latest version from this repo.  Trying to track down the error, I can't find it yet!

(Ps, thanks for releasing this awesome app, can't wait to use it!)

---

More info:

```
# around line 18
zinnia\admin\filters.py in lookups
        active_authors = Author.published.all().annotate( 

# around line 33
zinnia\managers.py in get_query_set
            entries__sites=Site.objects.get_current() 
```

**Comment by kolesnikovkhv** [comment]
Hi Fantomas, i got error 
Cannot resolve keyword 'flags' into field. Choices are: comment, content_type, content_type_id, id, ip_address, is_public, is_removed, object_pk, site, site_id, submit_date, user, user_email, user_id, user_name, user_url
i deleted database and re-create + call python manage.py syncdb
What could be the problem?

**Comment by kibe88** [comment]
@kolesnikovkhv hey, I was getting exactly the same error and it turned out that I forgot to install the django-contrib-comments app!

**Comment by JernejJerin** [comment]
That is correct. I was also migrating from 1.6 to 1.7. django.contrib.comments has been deprecated since 1.6, take a look in settings.py, if you still use django.contrib.comments. You need to replace it with django_comments.
