### ISSUE TITLE
TypeError: Author cannot proxy the swapped model 'app.User'

### ISSUE THREAD

**Issue by woutor** [Fantomas42/django-blog-zinnia#215]
Using Django 1.5, I have implemented a custom user model. Installing Zinnia then triggers the following exception:

```
TypeError: Author cannot proxy the swapped model 'app.User'
```

I also found this is a known limitation of Django: https://docs.djangoproject.com/en/dev/topics/auth/customizing/#custom-users-and-proxy-models. 

Any resolution would be appreciated.

**Comment by stefko18** [comment]
This is not resolved. I am still getting this with django 1.11.2 and zinnia 0.18.1 .. what might be the problem?
