### ISSUE TITLE
Moderated comment notification

### ISSUE THREAD

**Issue by bmeyer71** [Fantomas42/django-blog-zinnia#244]
Hey Julien,

Not sure what changed between 0.11.2 and 0.12.3, but if ZINNIA_AUTO_MODERATE_COMMENTS is set to True you do not get a notification of a new comment.  It does send an email notification if set to False, but that kind of defeats the purpose of moderation in this case.

Did I just miss something in the update between versions or is this truly broken?

I did take a look at the code between the two in moderator.py, but it looks the same so I don't see why it worked in 0.11.2 but not in 0.12.3

**Comment by mageshsugu** [comment]
Dear @Fantomas42 
    i am using zinnia 0.16
in my settings.py 
ZINNIA_MAIL_COMMENT_AUTHORS = True
ZINNIA_MAIL_COMMENT_REPLY = True
MANAGERS = [ ('member','m******@****.com'),('team','tn*****@***.com')]  # email me when a new comment is made
 ZINNIA_AUTO_MODERATE_COMMENTS = True

but i dont get mails for comments posted .
 but when i set ZINNIA_AUTO_MODERATE_COMMENTS  to  False mails are sent 
 i understand that we cannot send links to comments which are not posted public but i need atleast managers to get mails even ZINNIA_AUTO_MODERATE_COMMENTS = True
how can i do this

**Comment by mageshsugu** [comment]
Found solution
Modified moderator.py do email notification function
It works!!!
