### ISSUE TITLE
Exception Value: unorderable types: Entry() < Entry()

### ISSUE THREAD

**Issue by Fenkiou** [Fantomas42/django-blog-zinnia#343]
Hello,

I saw this subject : https://groups.google.com/forum/#!topic/django-blog-zinnia/u_NbDhh5zic but it seems that the person didn't create a new issue.

I'm encountering the same problem when I want to see recents articles. The problem doesn't appear to be on all articles, i don't know why..

I'm using python 3.4, Django 1.6.2 and Django-CMS 3.

This is the full traceback : 
http://pastebin.com/rX6LcgvN

Thanks for your attention.

**Comment by Fantomas42** [comment]
I thought it was Python 3 related but not, from my tests.

I close the issue, until further information.
