### ISSUE TITLE
wp2zinnia won't import images if they do not have a thumbnail

### ISSUE THREAD

**Issue by tomdickin** [Fantomas42/django-blog-zinnia#351]
A post can have an image attachment without having a thumbnail. If this is the case, then the importer will ignore that image.

The importer attempts to find the image ID like so:
```
#wp2zinnia.py line 340
if meta.find('{%s}meta_key' % WP_NS).text == '_thumbnail_id':
```
Where meta is a metadata element from the post itself.

If this isn't present the image attachment is completely ignored, as there is another offending line:
```
#wp2zinnia.py line 357
if post_type == 'post' and content and title:
```
Which means the entry will only be imported from here if it is a post.

Attachments can exist without the parent detailing them in their metadata. They simply contain the parent's ID within themselves like so:
```
<wp:post_parent>5153</wp:post_parent>
```

I'm not really sure how to go about fixing this cleanly.
All the obvious options I can think of have problems, those options being:
- Search for attachments across the whole document by a post's ID for each post (which would be insanely inefficient)
- Store a list of the imported posts and their IDs for when an attachment for it is encountered (that list could potentially be massive, so won't work for n many posts),
- Associate the image with an already stored post entry by some unique identifier from the original post object. As far as I can see it doesn't currently store anything we can be certain will be unique (other than the generated pk) that the image can use to add itself to an existing entry. If there currently isn't anything that stores the post's wp id then this would require changes to the model, which seems heavy handed.

Any suggestions?

**Comment by Fantomas42** [comment]
I have checked, and I have no easy solution.
I close the issue considering that is not real priority, but thank you for the feedback.
