### ISSUE TITLE
Overriding templates

### ISSUE THREAD

**Issue by shawn-simon-developer** [Fantomas42/django-blog-zinnia#359]
I've been trying to a bit to get Zinnia working on an existing Django website. Everything is finally up and running but I'm having trouble overriding the templates. For example, Zinnia uses `base.html` and that includes the `{% block sidebar %}` but when I go to override it, the changes I make are never rendered on the page.   

I've installed the `apptemplates` loader and added `'apptemplates.Loader',` to my `TEMPLATE_LOADERS`.  I've also tried using the `django-app-namespace-template-loader` the same way, with no results.

Additionally I have tried extending them using django overextends.

I've also ensured that I have the template directory I'm working with (`templates/`) added to my `TEMPLATE_DIRS`, and the directory structure looks like this:
    
    templates/

           classfied/                             <- Another custom app
                 some_other_templates.html

           zinnia/
                 base.html

My base.html looks like this:

    {% extends "zinnia:zinnia/base.html" %}
    {% load zinnia_tags i18n %}
    
    {% block sidebar %} 
    
      <p> OVERRIDED SIDEBAR </p>
    
    {% endblock sidebar %}

But alas, the sidebar is not changed. It's probably something small that I've missed, but I'm having a hard time debugging it. Any help is greatly appreciated. Let me know if you need any more information!

This isn't really an issue but hopefully it gets flagged as a question. 

Thank you!

**Comment by githubwoniu** [comment]
@shawn-simon-developer  @Fantomas42  @bittner 
I think the true answer is in django 1.8, we should set DIRS=[] of TEMPLATES in settings.py instead of TEMPLATE_DIRS, here is my solution

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'blog','templates'),
            os.path.join(BASE_DIR,'blog', 'templates', 'zinnia'),
        ],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 'zinnia.context_processors.version',  # Optional
            ],
			'loaders': [
                                'app_namespace.Loader',
				'django.template.loaders.filesystem.Loader',
                                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

wish this could help.
Best regards.
