### ISSUE TITLE
Template Documentation

### ISSUE THREAD

**Issue by b14ckkn19ht** [Fantomas42/django-blog-zinnia#383]
Hi,

I am currently trying to customize the templates to meet my webpage design and I am missing some Documentation on what is content and what is detail and how the templates work together. By now I tried to change the ... yeah I don't have a name, the <blog post itself>-template, where title, written by, the whole content etc. is shown. But my changes have influence on the list, and maybe other things.

What I was expecting:

entry_detail_base.html -> The Entries detail view (Title, meta information, everything of the post)
entry_list.html -> A list of entries. 

Maybe you can give me a hint or something on what file i could take as base file, and what's the difference between content and detail?

**Comment by bittner** [comment]
Yes, the `entry_detail_base` vs. `_entry_detail_base` and `entry_detail` vs. `_entry_detail` cases are a beast. I guess this is historically grown and cannot be changed easily without breaking backward compatibility in the templates.

Part of the "problem" is that with the [`content_template`](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/views/quick_entry.py#L67) variable there is some [flexibility built-in](http://django-blog-zinnia.readthedocs.org/en/latest/getting-started/configuration.html#templates-for-entries) (that I'm wondering who needs it). The rendering is done in blocks such as
``` python
{% include object.content_template with object_content=object.html_content %}
```
``` python
{% include object.content_template with object_content=object.html_preview continue_reading=1 %}
```
Examples:

* [entry_detail_base](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templates/zinnia/entry_detail_base.html#L38)
* [entry_search](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templates/zinnia/entry_search.html#L41)
* [entry_list](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templates/zinnia/entry_list.html#L93)

In the latter example, the `continue_reading` flag is [used for deciding](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templates/zinnia/_entry_detail_base.html#L57) whether to show a preview or the full article. `html_content` and `html_preview` are [properties of the entry model](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/models_bases/entry.py#L211) that handle the (potential) conversion to HTML and the necessarily complex truncation of HTML.

I think most people need to modify the `_entry_detail_base.html` template and don't need to touch `entry_detail_base.html` ever, for example. I believe some renaming of the template files would make things much much clearer. -- At the cost of breaking backward compatibility.

**Comment by Fantomas42** [comment]
@bittner thanks for your explanation.

I would add this information, the organization the ``_base.html`` suffix with inheritance is designed to ease the declination of different templates for rendering the entries. Using a base intermediary template make also the maintenance task a lot easier.

This design organization has been done after my own experience on http://darwin.willbreak.it, which required a lot of customization to represent the different kind of entries. And it was a real pain before this change.

Regards

**Comment by jdejoode** [comment]
To be honest I think this issue is not solved yet. The question is: how can one change the way articles are presented in a 'list' view (for instance, 5 most recent articles in cmsplugin_zinnia) without affecting the way these individual articles are presented in their 'detail' view. 

For instance: how can one have the entry-footer in the detail view, but not a list view.

**Comment by Fantomas42** [comment]
If you change _entry_detail_base.html, it's affects by default the detail and list template used, because in zinnia/entry_detail_base.html and zinnia/entry_list.html, the same include in used. 

  {{ object.content_template }}

Change the include in zinnia/entry_detail_base.html to point to the same template each time.

Regards

**Comment by jdejoode** [comment]
That did the trick! It did take a lot of experimenting. In my view the name "detail" should be reserved for templates that are old school detail views. Thanks for the pointer.
