### ISSUE TITLE
Plugins design issue?

### ISSUE THREAD

**Issue by tonioo** [Fantomas42/django-blog-zinnia#385]
Trying to fix a weird bug on my weblog, I've just realized that it is not possible to use zinnia-wysiwyg-ckeditor and zinnia_twitter in the same project. The cause of this issue is that both plugins unregister the current "Entry" admin class to register a custom EntryAdmin class... So, the first plugin declared into INSTALLED_APPS registers its own custom class, then the second one unregisters the current class (so the one of the first plugin) to register its own. I guess this issue will happen with another combination of plugins.

Am I the first one to fall into this ?

**Comment by Fantomas42** [comment]
Effectively if you use several plugins that enrich the admin, they are not all enabled by default.

But it's possible to fix that manually, by using the mixins provided in each package to construct the final admin. 

Something like this in your case:

    from zinnia_ckeditor.admin import EntryAdminCKEditorMixin
    from zinnia_twitter.admin import EntryAdminTwitterMixin
    from zinnia.admin.entry import EntryAdmin

    class FinalEntryAdmin(EntryAdminCKEditorMixin,
                                         EntryAdminTwitterMixin,
                                         EntryAdmin):
        pass

    admin.site.unregister(Entry)
    admin.site.register(Entry, FinalEntryAdmin)

I will add a note on the README of zinnia-twitter, to avoid future issues.
