### ISSUE TITLE
Exception 'admin/js/core.js' could not be found with CachedStaticFilesStorage

### ISSUE THREAD

**Issue by drbone** [Fantomas42/django-blog-zinnia#391]
During update to django 1.7.3 and django-blog-zinnia 0.15.1 I find out that if 
```
DEBUG = False
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
```
then any management command fails with error
```
The file 'admin/js/core.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x108213450>.
```
With default storage or in debug mode all works fine. Seems like the problem with staticfiles_storage.url() in admin/widgets.py in that case.

**Comment by narayanaditya95** [comment]
I face the same issue with django-blog-zinnia 0.15.1 with django 1.8.2. How do I solve this issue?
