### ISSUE TITLE
FieldError

### ISSUE THREAD

**Issue by kolesnikovkhv** [Fantomas42/django-blog-zinnia#393]
Hi Fantomas,
I got error:
Cannot resolve keyword 'flags' into field. Choices are: comment, content_type, content_type_id, id, ip_address, is_public, is_removed, object_pk, site, site_id, submit_date, user, user_email, user_id, user_name, user_url
I deleted the database and created again, after performing syncdb

**Comment by kolesnikovkhv** [comment]
the answer is simple: I forgot to add    'django_comments',

**Comment by Fantomas42** [comment]
Lol, you're welcome.

**Comment by cylussec** [comment]
Sorry... what was the fix? I am running into this after an upgrade.

**Comment by Fantomas42** [comment]
The installation of the django-contrib-comments was missing.

**Comment by cylussec** [comment]
Ahh... I thought it was something missing in my database. For anyone having this issue in the future, you have to install django-contrib-comments, and change the installed apps as indicated [here] (http://django-contrib-comments.readthedocs.org/en/latest/porting.html)
