### ISSUE TITLE
Installed Zinnia, now what?

### ISSUE THREAD

**Issue by Hiieu** [Fantomas42/django-blog-zinnia#396]
I have the application installed and everything seems to be working properly, including all the features in the admin panel.
But what should I put in my html? The documentation only mention about customizing templates.

**Comment by Fantomas42** [comment]
You put what you want in the content field.
HTML, text, markdown, textile, rst....

**Comment by Hiieu** [comment]
Wow, you explained very well! Great job.

**Comment by nim65s** [comment]
maybe with a more precise question you would have had a more precise answer…

**Comment by Hiieu** [comment]
He said to to HTML, text, markdown, textile, rst etc., but how to to that? He didn't explained that.
