### ISSUE TITLE
Some URLs inside published article lead to huge memory/CPU usage

### ISSUE THREAD

**Issue by fishi0x01** [Fantomas42/django-blog-zinnia#403]
**The Issue:**
When I save an article as "published", a certain URL embedded inside the entry makes my Apache worker allocate insane amounts of memory (+1.5G) and a CPU usage of 100% until I restart the Apache server. 

**Reproduction:**

1. So far I only found one URL which triggers the issue: add <pre>&lt;a href="http://mirrors.jenkins-ci.org/war/latest/jenkins.war" &gt; jenkins.war &lt;/a&gt;</pre> to an article's content. 

2. Store the article with "Save and continue editing" button as "published" 

3. (Sometimes this behavior doesn't occur, but for me it happens latest after 3 retries with about 15 sec waiting between each try)

**My Guess:**
It is interesting that this only happens when the article is being stored as "published". 
Also, the entry is perfectly stored, even after Apache has been restarted at some point.
I guess this might be a clue that this is somehow related to some worker that is triggered on embedded URLs when an article is being published (maybe trackback/pingback related???). 

**Environment:**
Debian7
Apache 2.x with mod_wsgi
Python 2.7
Django 1.7.3
django-blog-zinnia 0.15.1
Tackbacks/Pingbacks are disabled on my entries.

**Comment by fishi0x01** [comment]
**Update:**
It seems that the issue does not arise when I use the django dev server. 

I made some tcpdumps and saw, that both Apache and Django dev Server start downloading the jenkins.war when saving the article as published. 

Still, when using Apache, my memory and CPU go through the roof until I restart Apache.

**Comment by fishi0x01** [comment]
**Quickfix:**
Setting `ZINNIA_PING_EXTERNAL_URLS = False` fixes the issue for me, which means in my case this is very likely to be pingback related.

**Comment by DavidARussell** [comment]
Downloading the article is probably so that it can be parsed to check for a pingback auto-discovery URL. If I remember right, pingback consists of a tag within the source along the lines of `<meta rel="pingback-url" content="http://whatever" />`

**Comment by Fantomas42** [comment]
Okay I need to check how to avoid this kind of issue.
Because downloading 65Mo is not a really good idea, even if it does not explains the 1.5G of memory usage.

But with these datas it's an interesting test case.

**Comment by Fantomas42** [comment]
During my tests the content-type of http://mirrors.jenkins-ci.org/war/latest/jenkins.war

Was at first : text/plain; charset=utf8
And now : application/java-archive
