### ISSUE TITLE
NoReverse for all urls

### ISSUE THREAD

**Issue by percy3d** [Fantomas42/django-blog-zinnia#404]
Hello,

I just imported my wordpress posts and that went fine enough but I'm having an issues with django 1.7 and django-blog-zinnia (0.15.1). The following urls fail a reverse lookup:

'zinnia_entry_archive_year'
'zinnia_entry_archive_month'
'zinnia_entry_archive_day'
'zinnia_tag_detail'

I included the urls as documented:

url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
url(r'^comments/', include('django_comments.urls')),

Any help would be appreciated.

**Comment by percy3d** [comment]
Actually figured it out. urls in django 1.7 need to have a colon between the namespace and the url name like so: zinnia:entry_archive_year, zinnia:entry_archive_month

Maybe there's a setting in django to keep the underscore as a working solution or I missed something in the documentation but that is what I had to do.

Please let me know if there's a different way to go about fixing this issue.

**Comment by Fantomas42** [comment]
Hello,

yeah since v0.15 Zinnia use namespace to resolve his URLs.

The real question is, from where the resolution of zinnia_tag_detail is coming ? 
From a custom template, or a builtin templates ?

Regards

**Comment by percy3d** [comment]
It's actually from zinnia_foundations templates zinnia_foundation/templates/zinnia

**Comment by Fantomas42** [comment]
Okay this issue is related to https://github.com/django-blog-zinnia/zinnia-theme-foundation/issues/1

**Comment by Fantomas42** [comment]
@percy3d 
I have take a look on the problem.
If you use the last release from github of zinnia-theme-foundation, everything should be okay.

I have asked for a new stable release of zinnia-theme-foundation.

Regards
