### ISSUE TITLE
Zinnia on django 1.8

### ISSUE THREAD

**Issue by dingosaurus** [Fantomas42/django-blog-zinnia#405]
My stack is django 1.8beta, python 3.4.
When I visit page /backoffice/zinnia/entry/add/ I get:

```
env/lib/python3.4/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19:

19: {{ field.field }}

Exception Type: AttributeError at /backoffice/zinnia/entry/add/
Exception Value: 'str' object has no attribute '_meta'
```

Full traceback is on http://dpaste.com/05EDN5Q

Thanks 
Martin

**Comment by dingosaurus** [comment]
Problematic point found:
I use django mptt 0.6.1!
zinnia.admin.forms:EntryAdminForm contains some MPTT magic and field *categories* is returned as string...

Thanks

**Comment by datakid** [comment]
@dingosaurus what was the solution? Did you download the latest MPTT code and build or ...?

**Comment by Fantomas42** [comment]
Duplicate of #411
