### ISSUE TITLE
coveralls.io needs OAuth authorization renewal

### ISSUE THREAD

**Issue by Zopieux** [Fantomas42/django-blog-zinnia#407]
>Source Not Available
>
>The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

**Comment by PikachuEXE** [comment]
See https://github.com/lemurheavy/coveralls-public/issues/375

**Comment by Fantomas42** [comment]
Thanks for the report, it's now fixed !
