### ISSUE TITLE
"django_content_type" does not exist

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-blog-zinnia#408]
I've got a fresh Django 1.8 installation,  in a virtualenv with all deps successful. Running on Ubuntu 14.04.2 fwiw.

The settings is pretty much default - apart from the db settings and the zinnia needs I've not added anything (actually, not true - Django 1.8 has no 'django.contrib.sites' in INSTALLED_APPS - needed to add that).  'django.contrib.contenttypes' is in INSTALLED_APPS by default.

But I'm getting the error:

django.db.utils.ProgrammingError: relation "django_content_type" does not exist

?

Full output below:

(df)datakid@coburg:~/www/df/df-site$ python manage.py migrate
/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django_comments/__init__.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django_comments/models.py:2: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django_comments/models.py:46: RemovedInDjango19Warning: Model class django_comments.models.Comment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Comment(BaseCommentAbstractModel):

/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django_comments/models.py:165: RemovedInDjango19Warning: Model class django_comments.models.CommentFlag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CommentFlag(models.Model):

/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django_comments/forms.py:3: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  from django.forms.util import ErrorDict

System check identified some issues:

WARNINGS:
zinnia.Entry.categories: (fields.W340) null has no effect on ManyToManyField.
zinnia.Entry.related: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Synchronize unmigrated apps: staticfiles, mptt, messages, django_comments, tagging
  Apply all migrations: sessions, admin, sites, auth, contenttypes, zinnia
Synchronizing apps without migrations:
  Creating tables...
    Creating table django_comments
    Creating table django_comment_flags
    Creating table tagging_tag
    Creating table tagging_taggeditem
    Running deferred SQL...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" does not exist

**Comment by datakid** [comment]
I'm wondering if the unmaintained state of django-tagging has finally caught up with it? Has Django 1.8 introduced something new that has broken django-tagging?

**Comment by datakid** [comment]
Because of django-tagging's age, it hasn't been updated for Django migrations. Which is the most likely cause of the issue. Zinnia need to move to a new tagging dep or make the necessary changes to django-tagging.

**Comment by datakid** [comment]
Looks like there is some success with replacing django.contrib.contenttypes.generic with django.contrib.contenttypes.fields in the tagging app....

**Comment by datakid** [comment]
I edited ~/.virtualenvs/df/lib/python2.7/site-packages/tagging/models.py like so:

8 #from django.contrib.contenttypes import generic
9 from django.contrib.contenttypes.fields import GenericForeignKey

and 

487     #object = generic.GenericForeignKey('content_type', 'object_id')
488     object = GenericForeignKey('content_type', 'object_id')

I ran migrate again and got this error:

django.db.utils.ProgrammingError: relation "django_site" does not exist


Which I solved by:

$ python manage.py migrate zinnia
System check identified some issues:

WARNINGS:
zinnia.Entry.categories: (fields.W340) null has no effect on ManyToManyField.
zinnia.Entry.related: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: zinnia
Running migrations:
  Rendering model states... DONE
  Applying sites.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying zinnia.0001_initial... OK


and then
$ python manage.py migrate
WARNINGS:
zinnia.Entry.categories: (fields.W340) null has no effect on ManyToManyField.
zinnia.Entry.related: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Synchronize unmigrated apps: staticfiles, mptt, messages, django_comments, tagging
  Apply all migrations: sessions, admin, sites, auth, contenttypes, zinnia
Synchronizing apps without migrations:
  Creating tables...
    Creating table django_comments
    Creating table django_comment_flags
    Creating table tagging_tag
    Creating table tagging_taggeditem
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying admin.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK


Good to go from the look of it.

**Comment by Fantomas42** [comment]
Hello,

I have tested on Django 1.8 a migrate command, from an existing database and from scratch, and no issue occured.

Effectively django-tagging seems outdated, but do not cause issue.

So I close the ticket.

**Comment by alflanagan** [comment]
FYI: I'm seeing this on "python manage.py test", tried it on both the master and feature/django-1.8 branches. Apologies for the short report, no time, can post more details later.

**Comment by erickpeirson** [comment]
I'm also running into this issue, Django 1.8 on OSX 10.10.3, using psycopg2. I was able to get ``syncdb`` to run after deleting old migrations, but ``test`` still results in the error 
```
django.db.utils.ProgrammingError: relation "concepts_concept" does not exist
```

**Comment by erickpeirson** [comment]
I'm also seeing this, Django 1.8 on OSX 10.10.3 using psycopg2. I was able to get ``syncdb`` to run successfully after deleting old migrations, but ``test`` still results in
```
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
```

**Comment by Fantomas42** [comment]
@erickpeirson have you tried with the latest stable version of django-tagging ?

**Comment by moniq** [comment]
I had the same problem, 
I run: 
migrate auth
migrate contenttypes
migrate sites
migrate
and is working... 
Could someone explain me why this 'intuitive' solution works?

**Comment by Fantomas42** [comment]
The issue is coming from django-tagging using django.contrib.contenttypes.
Contenttypes was not using migrations before Django 1.8 and tagging neither.

So when the migrate occurs, Django do a syncdb on models without migrations, but because contenttypes has now migrations, the creation of the tables for tagging could not work anymore.

Since tagging use migrations and know his dependency to contenttypes, the issue does not occurs anymore when creating a fresh database.

**Comment by darkpixel** [comment]
I'm not using django-tagging, and am getting the same error message after upgrading to Django 1.8.x.  How in the heck can I identify the app that is causing problems?  The issue only rears its ugly head when running tests.  Since I obviously write flawless code, it's a minor annoyance.  ;)

**Comment by erickpeirson** [comment]
@darkpixel, the explanation given by @Fantomas32 is probably relevant in your case, minus the tagging bit. If I recall correctly, the test runner does syncdb. Are you running makemigrations before testing?

**Comment by darkpixel** [comment]
Yeah.  I finally figured it out by slowly removing every app from my INSTALLED_APPS.  Tracked it down to the latest version of django-attachments.  Fortunately I was using it for one minor feature, so I disabled it temporarily.

The error message is a bit vague and the traceback doesn't tell you which app is blowing up.  ;)

**Comment by he11ofr1end** [comment]
Hi guys!Have the same error, when trying to use 2 PostgreSQL databases.Did everything like in Django documentation,but got that error.
Django==3.1.1
