### ISSUE TITLE
Installation docs incomplete

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-blog-zinnia#409]
Unless I'm missing something, there seems to be a bunch of stuff missing from the installation documentation.

The process I followed up to the installation docs was:
 - create a virtualenv, db
 - pip install django, psycopg2, django-blog-zinna
 - create project, add db details to settings...start install process:

1. as I noted yesterday in #408, there are some minor issues with the tagging software that will be easy to fix.
2. Sync doesn't work out of the box, needed to explicitly sync zinna first, then in general. Potentially there should be a db sync *before* zinna is added to the INSTALLED_APPS setting?
3. settings.py no longer comes with SITE_ID - needed to add it, and because it's not really used any more, I needed to shell in and fix the site's details (from example.com to domain.com)

**Comment by Fantomas42** [comment]
Thanks for your report but like explained in the documentation I assume that you already have an installed Django project.

For the other points:

1. it will be fixed
2. weird it need some test
3. it will be precised in the documentation

Regards
