### ISSUE TITLE
Django 1.8 throws AttributeError at /admin/zinnia/entry/add/  'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-blog-zinnia#411]
I'm getting an error when I try to add a new entry in a fresh installation. I have no idea where to even start with this. 

Here is the traceback:

```
Environment:

Request Method: GET
Request URL: http://url.org/admin/zinnia/entry/add/

Django Version: 1.8
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django_comments',
 'mptt',
 'tagging',
 'zinnia_bootstrap',
 'zinnia')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Template error:
In template /path/to/.virtualenvs/df/local/lib/python2.7/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19

   'str' object has no attribute '_meta'

   9 :             {% for field in line %}
   10 :                 <div{% if not line.fields|length_is:'1' %} class="field-box{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
   11 :                     {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
   12 :                     {% if field.is_checkbox %}
   13 :                         {{ field.field }}{{ field.label_tag }}
   14 :                     {% else %}
   15 :                         {{ field.label_tag }}
   16 :                         {% if field.is_readonly %}
   17 :                             <p>{{ field.contents }}</p>
   18 :                         {% else %}
   19 :                              {{ field.field }} 
   20 :                         {% endif %}
   21 :                     {% endif %}
   22 :                     {% if field.field.help_text %}
   23 :                         <p class="help">{{ field.field.help_text|safe }}</p>
   24 :                     {% endif %}
   25 :                 </div>
   26 :             {% endfor %}
   27 :         </div>
   28 :     {% endfor %}
   29 : </fieldset>
```

**Comment by datakid** [comment]
Here's the rest of the error:

`
/path/to/.virtualenvs/df/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py in render
                        rel_opts = self.rel.to._meta
     ...

▼ Local vars
Variable 	Value
name	'categories'
self 	<django.contrib.admin.widgets.RelatedFieldWidgetWrapper object at 0xf5b5892c>
args 	()
IS_POPUP_VAR 	'_popup'
value  None
kwargs 	{'attrs': {u'id': u'id_categories'}}
TO_FIELD_VAR  '_to_field'

**Comment by datakid** [comment]
Variable 	Value
name 	'categories'

self 	<django.contrib.admin.widgets.RelatedFieldWidgetWrapper object at 0xf5b5892c>

args 	()

IS_POPUP_VAR 	'_popup'

value 	None

kwargs 	{'attrs': {u'id': u'id_categories'}}

TO_FIELD_VAR 	'_to_field'

**Comment by datakid** [comment]
'''
django.contrib.admin.widgets.RelatedFieldWidgetWrapper object at 0xf5b5892c
'''

**Comment by datakid** [comment]
Sure enough, commenting out lines 72 and 73 in zinnia/admin/forms.py allows the page to render. So we know where the error starts.
```python
55 class EntryAdminForm(forms.ModelForm):
 56     """
 57     Form for Entry's Admin.
 58     """
 59     categories = MPTTModelMultipleChoiceField(
 60         label=_('Categories'), required=False,
 61         queryset=Category.objects.all(),
 62         widget=MPTTFilteredSelectMultiple(_('categories'), False,
 63                                           attrs={'rows': '10'}))
 64 
 65     tags = TagField(
 66         label=_('Tags'), required=False,
 67         widget=TagAutoComplete())
 68 
 69     def __init__(self, *args, **kwargs):
 70         super(EntryAdminForm, self).__init__(*args, **kwargs)
 71         rel = ManyToManyRel(Category, 'id')
 72         #self.fields['categories'].widget = RelatedFieldWidgetWrapper(
 73          #   self.fields['categories'].widget, rel, self.admin_site)
 74 
```

Does this mean that the underlying MPTTFilteredSelectMultiple widget is returning the object as a str instead of as a model?

**Comment by ZuluPro** [comment]
Hello, I experienced the same issue with Django 1.8 and Zinnia fresh install.
After delete lines 72-73 the problem doesn't appear anymore.

@Fantomas42
Can you valid this modification doesn't break anything ?

**Comment by datakid** [comment]
FWIW, I don't think this is a good solution. Those lines of code are useful for representing the categories as trees (because categories can have parents) in the interface. 

I merely showed it to be true to help with the debugging process - it was as far as I got before I was out of my depth. I  was reporting back to make @Fantomas42 's job easier :) 

So, yes the solution works, but I don't think it is a *good* solution, just a functional one in the short term.

**Comment by ZuluPro** [comment]
@datakid: Ok, Thanks for your analysis.

**Comment by datakid** [comment]
NP, thanks for your work!

------

I'm treading carefully
but it's the time of night
the snowy light
the subway roar
and the whispered fights
exciting sights
but it's not enough
I thought it was
I wish it was
I thought it was
-----
You name it - The Cannanes with Explosion Robinson.

**Comment by Fantomas42** [comment]
@datakid effectively it works with your correction, but we cannot add categories anymore directly from the entry page.

A correction is planned, but it's not really easy.

**Comment by Fantomas42** [comment]
A WIP patch, which has the advantage for being compatible for Django 1.7 and 1.8

```diff
diff --git i/zinnia/admin/forms.py w/zinnia/admin/forms.py
index 86c2985..5ef202c 100644
--- i/zinnia/admin/forms.py
+++ w/zinnia/admin/forms.py
@@ -63,7 +63,7 @@ class EntryAdminForm(forms.ModelForm):
 
     def __init__(self, *args, **kwargs):
         super(EntryAdminForm, self).__init__(*args, **kwargs)
-        rel = ManyToManyRel(Category, 'id')
+        rel = Entry.categories.field.rel
         self.fields['categories'].widget = RelatedFieldWidgetWrapper(
             self.fields['categories'].widget, rel, self.admin_site)
 

```

**Comment by datakid** [comment]
What is WIP?

**Comment by Fantomas42** [comment]
Work In Progress :hourglass:
