### ISSUE TITLE
Django 1.8 problem

### ISSUE THREAD

**Issue by mrgaolei** [Fantomas42/django-blog-zinnia#412]
./manage runserver:

There is no South database module 'south.db.mysql' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

**Comment by datakid** [comment]
Django moved to a migrations infrastructure from version 1.7, which deprecated the need for South.

FWIW, migrations are easier and more powerful than South, and have been written by the author of South - in fact his work means he's now a core contributor to the Django code base.  

So the error you are seeing is unlikely to be related to Zinnia - I've installed this app in a new Django 1.8 installation and got no South errors to my knowledge.

I would recommend removing South from your installed apps.

The [Django docs](https://docs.djangoproject.com/en/1.8/) have [a section dedicated to the new migrations](https://docs.djangoproject.com/en/1.8/topics/migrations/) which include a part on [upgrading from South](https://docs.djangoproject.com/en/1.8/topics/migrations/#upgrading-from-south)

**Comment by mrgaolei** [comment]
My project didn't use South

**Comment by mrgaolei** [comment]
I create a new project with django 1.8, but when I add zinnia to INSTALLED_APPS, the problem prompted.

My clean settings.py:

`
"""
Django settings for fmit project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1(_l=(d46=nf@vvi2ruoo15ll1208x0(l2n9!5ou)xa+k9+q=*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'zinnia',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'fmit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fmit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fmit2',
        'USER': 'fmit',
        'PASSWORD': 'andrewlblb',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
`

**Comment by datakid** [comment]
Might be worth checking by setting up a new project. This is a weird error to get.

**Comment by Fantomas42** [comment]
Your settings reflect that you didn't installed the zinnia app correctly.

This issue is related to a misconfiguration IMO.

Regards

**Comment by Beautiful-Skyline** [comment]
'fmit.zinnia',
