### ISSUE TITLE
14.1 does not work with MySQL with zinnia.views.archives.EntryIndex

### ISSUE THREAD

**Issue by jontyneedham** [Fantomas42/django-blog-zinnia#413]
Error:
ValueError at /testing
Database returned an invalid value in QuerySet.datetimes(). Are time zone definitions for your database and pytz installed?

Steps to reproduce:
Use MySQL as django db backend.
Set urls to go to EntryIndex from archives.
Add a blog.
Refresh to list new content. -- fails.

The MySQL passed into django contains an error:
SELECT DISTINCT CAST(DATE_FORMAT(CONVERT_TZ(`zinnia_entry`.`creation_date`, 'UTC', UTC), '%Y-01-01 00:00:00') AS DATETIME) FROM `zinnia_entry` INNER JOIN `zinnia_entry_sites` ON ( `zinnia_entry`.`id` = `zinnia_entry_sites`.`entry_id` ) WHERE ((`zinnia_entry`.`start_publication` <= 2015-04-13 09:51:27  OR `zinnia_entry`.`start_publication` IS NULL) AND (`zinnia_entry`.`end_publication` > 2015-04-13 09:51:27  OR `zinnia_entry`.`end_publication` IS NULL) AND `zinnia_entry`.`status` = 2  AND `zinnia_entry_sites`.`site_id` = 1 ) ORDER BY 1 DESC LIMIT 21

I have migrated, set the timezone etc.  This also fails if the timezone is "Europe/London". I've not found a timezone that works yet, even if that were to be the problem.

**Comment by jontyneedham** [comment]
This is not a bug with zinnia, this is a "feature" of MySQL whereby the timezones are not loaded by default. You have to load them with:
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

**Comment by Fantomas42** [comment]
Okay perfect if you have found the solution !

Regards
