### ISSUE TITLE
Can't modify erroneous German translations on Transifex

### ISSUE THREAD

**Issue by bittner** [Fantomas42/django-blog-zinnia#421]
Some of the translations to German are wrong, unfortunately. I'd like to correct them but even though I'm in the list of translators on [Transifex](https://www.transifex.com/projects/p/django-blog-zinnia/language/de/) I can't edit them anymore. Probably, because the text segements are already reviewed and I'm not in the list of the reviewers. Can you help, @Fantomas42 or @jezdez?

The issues I've found (and commented on a year ago) are related to [featured entries](https://www.transifex.com/projects/p/django-blog-zinnia/translate/#de/djangopo/10629452?q=featured).

**Comment by Fantomas42** [comment]
Hi @bittner,

I have put you the role of reviewer on Transifex, tell me if it's good for you.

Regards

**Comment by bittner** [comment]
That worked out, thank you!

I have now corrected the translations. But I'd prefer that someone else [reviewed them](https://www.transifex.com/projects/p/django-blog-zinnia/translate/#de/djangopo/39368984?reviewed=no) rather than myself. @jezdez, would you?

**Comment by jezdez** [comment]
sure

**Comment by bittner** [comment]
@jezdez please don't forget! I'd love to see the updated translation in the next release or so.

Specifically, watch out for "backlink" that I translated as "Rückwärtslink".
