### ISSUE TITLE
Default WYMEditor not working - neither am I able to install TINYMCE

### ISSUE THREAD

**Issue by fuatse** [Fantomas42/django-blog-zinnia#422]
Using Python 2.7 and Django 1.8, I just installed the latest version of Zinnia. 

To create entries, the content field is just a simple text area meaning the default WYMEditor is not working even when i explicit put that in the settings.py file.

Also tried to install TINYMCE but will not work. 

Any thoughts on that ?

**Comment by Fantomas42** [comment]
I think is related to this issue https://github.com/django-blog-zinnia/zinnia-wysiwyg-wymeditor/issues/1
