### ISSUE TITLE
Make templatetags more generally usable

### ISSUE THREAD

**Issue by bittner** [Fantomas42/django-blog-zinnia#423]
Zinnia's [template tags](/Fantomas42/django-blog-zinnia/blob/develop/zinnia/templatetags/zinnia.py#L52) are very useful for customized solutions. Though, some limitations are maybe unnecessary and could be removed.

We found this as we were integrating Zinnia into another web project.

## More generic context

The functions `get_categories`, `get_categories_tree`, `get_authors` have an additional `context_category` and `context_author`. Unfortunately, `category` and `author` are not always available in the context, e.g. in a blog entry detail. (In this case the `context_*` value is `None`, of course.)

The singular of the words `context_author` and `context_category` suggests that the tags are designed for the following use cases:

1. Highlight the currently visited category (or author page) in a list of categories or authors.
1. Show a list of all published, non-empty categories (or authors) anywhere, no highlighting of any item implied.

However, there is an additional, maybe not too uncommon use case that is not yet covered:

* Show a list of categories (or authors) on a blog **entry detail** ~~or blog **entry list** page~~,
* and highlight **all categories** (or authors) used in the entry ~~or entry list~~.

The values missing in the context for this use case can be provided by:
```
    try:
        entry_categories = context.get('object').categories.all()
    except AttributeError:  # no object in the context
        entry_categories = None
```

There may be other, similar use cases also for the other tags.

**Comment by Fantomas42** [comment]
Ok I see your idea, it could be an interesting possibility of customization for the theme, but I have 2 points to highlight:

* How can I have the list of categories or authors used in the case of an **entry list** page ?
* I don't like the context.get('object').categories.all() because it will lead to a new query and executed 50% of the time without results...

A solution for the second point could be to pass as arguments the list of categories, but it appears to be impossible without doing another DB query... 

Note this behavior should also apply to ``get_tag_cloud``.

**Comment by bittner** [comment]
You're right regarding the entry list: There's no need of additional context data there.

**Comment by Fantomas42** [comment]
I close the issue, waiting for an implementation/PR to continue the discussion on code.

Note, I'm not in favor of adding another new DB query to these template_tags, the implementation should avoid this as long as possible.

**Comment by bittner** [comment]
I was wondering if you had a proposal of adding additional data (e.g. categories) to the context on all pagesl. More data in the context when not used often is not beautiful, but that would avoid the additional query in the tag (if the data can be acquired together with some other query). I thought you would know best.
