### ISSUE TITLE
Infinite scrolling instead of pagination (as an option)

### ISSUE THREAD

**Issue by bittner** [Fantomas42/django-blog-zinnia#424]
It would be nice to have Infinite Scrolling built-in into Zinnia as an alternative to traditional pagination of entry lists.

* a settings option `ZINNIA_INFINITE_SCROLLING = (True|False)` could be introduced 
* the value of `ZINNIA_PAGINATION` should be re-used for the number of items to load initially and when reaching the bottom of the page

## Possible Solution Pieces

* Implementing a simple `ListView` returning a sliced result, e.g.
```
    start = page * settings.ZINNIA_PAGINATION
    entries = ...
    entries[start:start + settings.ZINNIA_PAGINATION]
```
* Using the unmaintained [infinite-scroll jQuery plugin](http://stackoverflow.com/questions/26600216/how-to-implement-infinite-scroll-endless-pagination-using-the-zinnia-blog-app-f).
* Using the [jScroll – jQuery Plugin for Infinite Scrolling](http://plugins.jquery.com/jscroll/).
* Using [django-endless-pagination](https://github.com/frankban/django-endless-pagination) and its [pagination on scroll](http://django-endless-pagination.readthedocs.org/en/latest/twitter_pagination.html#pagination-on-scroll).

**Comment by Fantomas42** [comment]
It would be nice, but this kind of feature is against my philosophy on the project:

- I want minimal JS on the default skin.
- I don't want to impose a choice of a JS library
- I don't want to do JS (each time I used a JS library, I have to maintain it at some time)

For me this kind of feature should be located at the integration level, when the developer integrate the templates into his website. Zinnia should be agnostic on how to handle the pagination.

In another side, I have done this on my personal weblog, in 10min with the now unmaintained infinite-scroll JQuery plugin, so they are no real interest to provide this feature pre-integrated.

Regards
