### ISSUE TITLE
ReStructured Text Quick links don't render

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-blog-zinnia#426]
I'm using ReStructured Text, and I've noticed that the quicklinks don't work as listed here: http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

External hyperlinks, like `Python <http://www.python.org/>`_.

is being rendered:

External hyperlinks, like `Python `_. with no hyperlink at all

**Comment by datakid** [comment]
Ok, looks like the other RST linking patterns don't work either. Is there a way to set the markup style?

**Comment by Fantomas42** [comment]
http://docs.django-blog-zinnia.com/en/develop/ref/settings.html#zinnia-markup-language

**Comment by datakid** [comment]
Ah yes - I did look for the docs. I presumed you knew that they don't work. At least, on my connection here in Australia.

django-blog-zinnia.com -> Server not found in Firefox; Webpage not available in Chromuim
 
docs.django-blog-zinnia.com -> Server not found in Firefox; Webpage not available in Chromuim

docs.django-blog-zinnia.com/en/develop/ref/settings.html#zinnia-markup-language -> doesn't stop loading in Firefox (but with no content); Webpage not available in Chromuim

Down for Everyone but me? Has Docs down:
http://downforeveryoneorjustme.com/docs.django-blog-zinnia.com

According to 404hecker (random site I found via google) the headers are ok:
http://404checker.com/status/docs.django-blog-zinnia.com

And if you use their header check, you can see the values:
http://404checker.com/header/docs.django-blog-zinnia.com


But I can't read the docs :/

Oh, wait. They're rst. I've sphinxed them locally. But yes, the online docs don't work.

**Comment by Fantomas42** [comment]
Ok I certainly need to renew the domain.

**Comment by Fantomas42** [comment]
I have renew the domain, everything should be okay in a few hours.
