### ISSUE TITLE
search throwing error on development version

### ISSUE THREAD

**Issue by bradrice** [Fantomas42/django-blog-zinnia#427]
I'm getting tis on my search:

NoReverseMatch at /blog/search/

This is what I have for blog in urls: 

url(r'^blog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),

Here is my site:

http://www.bradrice.com/blog/

Can you tell me if this is a bug or if I need to configure my installation?

**Comment by Fantomas42** [comment]
I see that you use zinnia_foundation, certainly the latest stable. Zinnia_foundation latest stable is not compatible with the latest version of Zinnia. 

Using the develop version of zinnia_foundation should resolve the issue.

**Comment by bradrice** [comment]
Well I did install the develop version. I guess I'll comment on their site if thisi is an issue with zinnia_theme_foundation.
