### ISSUE TITLE
'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by bradrice** [Fantomas42/django-blog-zinnia#428]
I thought this had been fixed in the newest version, but I keep getting this error on my local install.

'str' object has no attribute '_meta'

the location: /Users/brad2/Sites/bradweb/lib/python3.4/site-packages/django/contrib/admin/widgets.py in render, line 284

This is how I installed zinnia:

pip install -e git://github.com/Fantomas42/django-blog-zinnia.git#egg=django-blog-zinnia

**Comment by bradrice** [comment]
Also, when I runserver on local I get this:

WARNINGS:
zinnia.Entry.categories: (fields.W340) null has no effect on ManyToManyField.
zinnia.Entry.related: (fields.W340) null has no effect on ManyToManyField.

I can't figure out what I need to do here. How do I fix that warning?

**Comment by Fantomas42** [comment]
Check if you are on the develop branch after the pip install.

**Comment by bradrice** [comment]
How do I check the zinnia version? Thanks

**Comment by bradrice** [comment]
If I do pip list this is what I have. Is this an accurate way to get it?

beautifulsoup4 (4.3.2)
Django (1.8.2)
django-blog-zinnia (0.15.1, /Users/brad2/Sites/bradweb/src/django-blog-zinnia)
django-ckeditor (4.4.8)
django-contrib-comments (1.6.1)
django-mptt (0.7.3)
django-tagging (0.3.6)
django-xmlrpc (0.1.5)
mots-vides (2015.5.11)
Pillow (2.8.1)
pip (7.0.0)
pyparsing (2.0.3)
pytz (2015.4)
setuptools (3.6)
zinnia-theme-foundation (1.0.1)
zinnia-wysiwyg-ckeditor (1.2)

**Comment by Fantomas42** [comment]
pip install -e git://github.com/Fantomas42/django-blog-zinnia.git@develop#egg=django-blog-zinnia

**Comment by bradrice** [comment]
Thank you. Really awesome software.
