### ISSUE TITLE
No Reverse for 'tinymce-js' (again)

### ISSUE THREAD

**Issue by bastien34** [Fantomas42/django-blog-zinnia#431]
Hi, sorry if it may already asked but I sincerely can't figure out what's wrong since I believe having followed all installation steps of zinnia-wysiwyg-tinymce.
I get a no reverse for tinymce-js when I try to edit an entry in the admin panel.
Is there something related to the admin template?

**Comment by Fantomas42** [comment]
Do you have registered the URLs of tinymce, like described in the documentation ?

    (r'^tinymce/', include('tinymce.urls')),

Regards

**Comment by dilatgh** [comment]
zinnia-wysiwig-tinymce doesn't work. "tinymce-js" URL name and its view textareas_js  don't exist in django-tinymce anymore: https://github.com/aljosa/django-tinymce/commit/1535f5c33544c4ac49d397ec14e2ec88e177587d#diff-99f82678a1ffa0a31e0576ec938419c9

**Comment by Fantomas42** [comment]
Issue opened here https://github.com/django-blog-zinnia/zinnia-wysiwyg-tinymce/issues/6
