### ISSUE TITLE
NoReverseMatch exception after Entry's model extention

### ISSUE THREAD

**Issue by Lomand** [Fantomas42/django-blog-zinnia#433]
Despite the fact that I've done everything exactly the same as described in [documentation](http://docs.django-blog-zinnia.com/en/develop/how-to/extending_entry_model.html), I'm getting `NoReverseMatch` exception with my new custom `get_absolute_url` property on all pages  with references on another entries. 

```
NoReverseMatch at /blog/1/
Reverse for 'entry_detail' with arguments '()' and keyword arguments '{'pk': '1'}' not found. 1 pattern(s) tried: ['weblog/(?P<year>\\d{4})/(?P<month>\\d{2})/(?P<day>\\d{2})/(?P<slug>[-\\w]+)/$']
```
Here is the part of the template that cause error:
```
<a href="{{ object.get_absolute_url }}"></a>
```

zinnia_customized.models

```python
from django.db import models
from zinnia.models_bases.entry import AbstractEntry

class EntryWithNewUrl(AbstractEntry):
    """Entry with '/blog/<id>/' URL"""

    @models.permalink
    def get_absolute_url(self):
        return ('zinnia:entry_detail', (),
                {'pk': self.id})

    class Meta(AbstractEntry.Meta):
        abstract = True
```
zinnia_customized.views

```python
from django.views.generic.detail import DetailView

from zinnia.models.entry import Entry
from zinnia.views.mixins.entry_preview import EntryPreviewMixin
from zinnia.views.mixins.entry_protection import EntryProtectionMixin

class EntryDetail(EntryPreviewMixin,
                  EntryProtectionMixin,
                  DetailView):
    queryset = Entry.published.on_site()
    template_name_field = 'template'
```

urls.py
```python
from zinnia_customized.views import EntryDetail

url(r'^blog/(?P<pk>\d+)/$', EntryDetail.as_view(),  name='entry_detail'),
```

Project’s settings.py:
```python
ZINNIA_ENTRY_BASE_MODEL = 'zinnia_customized.models.EntryWithNewUrl'
```
If I remove `ZINNIA_ENTRY_BASE_MODEL ` from the settings file I could actually reach the entry with new url pattern, but  urls to other entries have standart `weblog/<year>/<month>/<day>/<slug>` format. (That's because custom `get_absolute_url()` is not registered, after all)

Is that some kind of bug or am I actually missing something?
Thanks in advance.

....  
Django 1.8.2
Zinnia 0.15.2.dev0
Python 3.4

**Comment by Fantomas42** [comment]
Do you have registered the custom URLs before the Zinnia URL's ? 
And the namespace is missing in the customs URLs.

If with this work when ZINNIA_ENTRY_BASE_MODEL commented, it's certainly coming from the short url view.

Note: from this documentation, http://docs.django-blog-zinnia.com/en/develop/how-to/rewriting_entry_url.html if you have read it correctly, I do not provide support on this feature.
