### ISSUE TITLE
trying to add django-image-cropping to Entry

### ISSUE THREAD

**Issue by devbollinger** [Fantomas42/django-blog-zinnia#434]
HI guys, i'm trying to use the django-image-cropping on an article image entry and i need some help on it.
Following the doc, i first create a new class in my blog models.py extending AbstractEntry:

    from zinnia.models_bases.entry import AbstractEntry
    from image_cropping import ImageRatioField

    class AddCroppingToImageEntry(AbstractEntry):
        cropping = ImageRatioField('image_entry', '1900x620')

        class Meta(AbstractEntry.Meta):
            abstract = True

I changed the migration modules path like so:

<code>
MIGRATION_MODULES = {
    'blog': 'blog.migrations.db_migration'
}
</code>

then i changed the entry base model:

<code>
ZINNIA_ENTRY_BASE_MODEL = 'blog.models.AddCroppingToImageEntry'
</code>
and i change the admin interface:

    from django.contrib import admin
    from django.utils.translation import ugettext_lazy as _
    from image_cropping import ImageCroppingMixin
    from zinnia.models import Entry
    from zinnia.admin import EntryAdmin

    class AddCroppingToImageEntryAdmin(EntryAdmin, ImageCroppingMixin):
        pass

    admin.site.register(Entry, AddCroppingToImageEntryAdmin)

doc for django-image-cropping can be found here: https://pypi.python.org/pypi/django-image-cropping
If someone has any idea, you are welcome to share!

**Comment by Fantomas42** [comment]
MIGRATION_MODULES = { 'zinnia': 'blog.migrations.db_migration' } 

is better no ?

I don't know this app, but where are you stuck ?

**Comment by devbollinger** [comment]
Hi Julien,

I just try the app with a normal imageField and it's seems to do not work properly, i thing i will use sorl_thumbnail for now, and i will try to find a cropping tool for my admin later.
Thank you for you reply.

Bye
