### ISSUE TITLE
New installation Django 1.8 - Models not loaded

### ISSUE THREAD

**Issue by ilovecraft** [Fantomas42/django-blog-zinnia#435]
I apologize if this is a duplicate. I looked around the blogs to see if this has been addressed already. I have tried multiple installations of Zinnia and all fail with the same error. When running syncdb I recieve the error: 
File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_comments',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'markdown_deux',
    'mptt',
    'tagging',
    'zinnia',
)

I have attempted to use pip install -U django-blog-zinnia and this completes successfully; but errors when running syncdb. I have made the tweaks mentioned in previous posts to the authors.py and __init__.py files but still receive the same error. 

Am I missing a work around somewhere?

**Comment by ilovecraft** [comment]
The issue was resolved by downloading the latest copy of django-mptt and replacing the one installed by pip. Unsure why they were different but Zinnia now executes flawlessly. Well done. Thanks.

**Comment by EmlynC** [comment]
Cheers for posting, this also helped me when I tried to add Zinnia to a django site that was already using a version of django-mptt. Upgrading to latest django-mptt with

```bash
pip install -U django-mptt
```

... fixed this for me.
