### ISSUE TITLE
Author USERNAME_FIELD with a custom user

### ISSUE THREAD

**Issue by RossLYoung** [Fantomas42/django-blog-zinnia#437]
With a custom user, it is sometimes necessary to set USERNAME_FIELD = 'email'. The Auth app needs to know what field to treat as unique.

This property breaks the Author lookups.

For the moment, I've added an additional property and changed the 16 references to it so I now have....

```
USERNAME_FIELD = 'email'
ZINNIA_USERNAME_FIELD = 'username'
```

What is the best approach here? Simply an additional property on the User/Author. Or perhaps a Author.get_username_field() method?

**Comment by Fantomas42** [comment]
Hello,

I just have understood the issue. But I don't find reference in Zinnia's codebase causing the issue.
Maybe I miss something.

Can you share your modifications ?

Regards

**Comment by Fantomas42** [comment]
Found this https://github.com/Fantomas42/django-blog-zinnia/compare/develop...RossLYoung:author-username-field

**Comment by Fantomas42** [comment]
Finally I don't understand why the Author lookup is broken.

If this field is unique, the lookup should work...

**Comment by Fantomas42** [comment]
Hello,

I have made some tests with https://github.com/jcugat/django-custom-user/ who represent well the described case, and no issue happen.

Who knows from where the issue came from.

Regards
