### ISSUE TITLE
404 on resources for documentation

### ISSUE THREAD

**Issue by caleb-allen** [Fantomas42/django-blog-zinnia#441]
Wasn't sure where to report this, I couldn't find any contact info for an email.

I'm getting a 404 on http://docs.django-blog-zinnia.com/en/develop/. Doesn't look like readthedocs.org or any readthedocs services are down.

**Comment by Fantomas42** [comment]
Fixed in https://github.com/Fantomas42/django-blog-zinnia/commit/df6d20752557c85d5efd1ce58debec464bae95f2
