### ISSUE TITLE
'zinnia' is not a registered namespace

### ISSUE THREAD

**Issue by Khailz** [Fantomas42/django-blog-zinnia#442]
I recieve when trying to make a new entry

NoReverseMatch at /admin/zinnia/entry/
'zinnia' is not a registered namespace

**Comment by ZuluPro** [comment]
What's the use that give it to you?
What is your Django/Zinnia version ?

**Comment by Khailz** [comment]
I'm using Django 1.8 and v08.1 of Zinnia I also tried with dev version

**Comment by Khailz** [comment]
Fixed... turns out I had an older version installed.

**Comment by ZuluPro** [comment]
Can you give the traceback of your error. If this bug is reproductible with new versions we should fix it.
