### ISSUE TITLE
window function call requires an OVER clause

### ISSUE THREAD

**Issue by datakid** [Fantomas42/django-blog-zinnia#443]
I don't know when this error started happening. 

I don't understand why it's happening either - when I try to debug, it seems endless?

This is the error I get on the front page of the blog:

Environment:
Django Version: 1.8.4
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.sites',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django_comments',
 'mptt',
 'tagging',
 'zinnia')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Template error:
In template /home/datakid/.virtualenvs/df/local/lib/python2.7/site-packages/zinnia/templates/zinnia/tags/entries_slider.html, error at line 2
   window function call requires an OVER clause
LINE 1: ...ingback_count", "zinnia_entry"."trackback_count", "zinnia_en...
                                                             ^
...
   2 :  {% if entries %} 
... 

Exception Type: ProgrammingError at /
Exception Value: window function call requires an OVER clause
LINE 1: ...ingback_count", "zinnia_entry"."trackback_count", "zinnia_en...
                                                             ^

I can see the admin site no problem, until I start trying to look at the entries, edit a particular entry or save a tagged entry?

On those occasions, I get the same error, except the problem is located at:

lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64

**Comment by Fantomas42** [comment]
This issue seems coming from the DB backend or from the Django's ORM.

I have just tested with a recent version of Django, but on sqlite3, and I cannot reproduce the issue.

Does the tests pass ?

Until more informations, I close the issue.

**Comment by jlmadurga** [comment]
I have the same issue when migration from zinnia 14 to 15.2

**Comment by eranrund** [comment]
The problem seems to be with `lead` being a PostgreSQL function that for some reason is not being quoted properly :( (http://www.postgresql.org/docs/current/static/functions-window.html)

**Comment by eranrund** [comment]
After digging more into this, this seems to happen only **before** zinnia is migrated to introduce the `lead` field to the table. After migrating, the problem disappears.
