### ISSUE TITLE
Add author to an entry using custom user model

### ISSUE THREAD

**Issue by Barnalite** [Fantomas42/django-blog-zinnia#444]
Hi,
I'm trying to bind an author to an entry using the django admin add form. When I save django throws an exception:
'Author' instance expected, got CustomModel.

Debuggin I see that the method _add_items of ManyRelatedManager class throws the exception because isinstance(obj, self.model) returns False. obj is my custom model class and self.model is zinnia.models.author.Author.

**Comment by Fantomas42** [comment]
OK I will try to reproduce the issue.

Normally your custom user is wrapped in the Author class to avoid this kind of issue.

Does your CustomModel add field to the User model, or override some fields ?

Regards

**Comment by Barnalite** [comment]
My custom model inherits from AbstractBaseUser and PermissionsMixin and defines its own fields

**Comment by sumeetpujara** [comment]
I am facing same issue.
I changed `AUTH_USER_MODEL` to a custom user model.
Now when I have an blog entry from django admin, error is raise.
`IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`admin`.`zinnia_entry_authors`, CONSTRAINT `zinnia_entry_authors_author_id_32129d58ee94e064_fk_auth_user_id` FOREIGN KEY (`author_id`) REFERENCES `auth_user` (`id`))')`

This shows that in database, author is in relation with default django user model, `auth_user`.
I couldn't create migration for zinnia by simply changing the  `AUTH_USER_MODEL` to customer user model.
Do I have to extended the zinnia entry model ?(for creating migration file)

**Comment by sumeetpujara** [comment]
My above comment is not an issue.
It can be solved writing custom migrations.
https://www.caktusgroup.com/blog/2013/08/07/migrating-custom-user-model-django/

**Comment by Fantomas42** [comment]
Effectively when using a custom User, using custom migrations should do the trick.
