### ISSUE TITLE
Issue about comments

### ISSUE THREAD

**Issue by YFZX** [Fantomas42/django-blog-zinnia#450]
hi,
When i trying to comment an example entry ,it happened to an error,i just start to learn django,so i need your help.Below is the error infomation.

error at /comments/post/
[Errno 111] Connection refused
Request Method:	POST
Request URL:	http://127.0.0.1:8000/comments/post/
Django Version:	1.8.5
Exception Type:	error
Exception Value:	
[Errno 111] Connection refused
Exception Location:	/usr/lib/python2.7/socket.py in create_connection, line 571
Python Executable:	/usr/bin/python

**Comment by Fantomas42** [comment]
http://docs.django-blog-zinnia.com/en/develop/getting-started/install.html#emails

**Comment by YFZX** [comment]
OK,thanks! I'ii check it and solve the problem.  :P
