### ISSUE TITLE
Feature to customize entry detail in loop template

### ISSUE THREAD

**Issue by joke2k** [Fantomas42/django-blog-zinnia#455]
Hi thank you for your beautiful work.

Reading the docs i found this:
```
But how can we specify a template for a given index position the list ? 
For example if we want to highlight the first entry.
Then we simply create a new template suffixed by a dash followed by the position.

Example: zinnia/_entry_detail-1.html 
 ```
but it seems not work. zinnia/_entry_detail_1.html neither...

**Comment by Fantomas42** [comment]
Do you use the develop version of Zinnia ?

**Comment by joke2k** [comment]
I'm using `django-blog-zinnia==0.15.2`

**Comment by Fantomas42** [comment]
This feature is for the moment only available in the develop version.

**Comment by joke2k** [comment]
oh, thank you.
When the new release will be published?

**Comment by Fantomas42** [comment]
The new release has just been published.
