### ISSUE TITLE
Website is dead

### ISSUE THREAD

**Issue by Zopieux** [Fantomas42/django-blog-zinnia#459]
http://django-blog-zinnia.com/ is dead.
Ping @Fantomas42!

**Comment by mafrosis** [comment]
This means there's currently no docs (short of search google cache)!

@Fantomas42 please can you take a look at this?

**Comment by morgante** [comment]
For now, I'm using Archive.org's copy: https://web.archive.org/web/20150923202538/http://docs.django-blog-zinnia.com/en/latest/getting-started/install.html

**Comment by gustavklopp** [comment]
+1
(and thanks a lot for the tip @morgante !)

**Comment by leotsem** [comment]
Looks like the documentation is also hosted on http://django-blog-zinnia.readthedocs.org.

**Comment by mafrosis** [comment]
Good find @leotsem

**Comment by Fantomas42** [comment]
The CNAME http://docs.django-blog-zinnia.com is now restored.

The demo website will be restored soon.

Regards

**Comment by Zopieux** [comment]
Thanks!

**Comment by jplehmann** [comment]
Still no demo.

**Comment by benjaoming** [comment]
Maybe someone wanting to contribute to the project could setup and maintain a free Heroku instance to lift this task off @Fantomas42 's shoulders?

**Comment by Fantomas42** [comment]
http://django-blog-zinnia.com/
http://demo.django-blog-zinnia.com/

Restored et updated to the last releases...
