### ISSUE TITLE
Markup language doesn't work in Lead

### ISSUE THREAD

**Issue by jplehmann** [Fantomas42/django-blog-zinnia#467]
Is there any reason why Markdown works for the content of my blog but not in the lead paragraph?  This is surprising and is a borderline bug.

For fuller context, I prefer to have most of the content of my blogs on my blog entries page, so users don't have to click into them. In order to do this, I'm putting that content in the lead.  If there's a setting or some other way to have this effect it could be a workaround.

**Comment by Fantomas42** [comment]
Hello @jplehmann 

the initial reason is that lead paragraph was conceived as a simple introduction of text, without stylization. But this will change in the next days.

For your requested presentation of the blog, the best option, is to override/extend the template zinnia/_entry_detail_base.html to display the 'content' and/or 'lead' fields directly, without notion of continue-reading...

Regards
