### ISSUE TITLE
argument of type 'NoneType' is not iterable in BlogDetail View

### ISSUE THREAD

**Issue by sachitad** [Fantomas42/django-blog-zinnia#471]
Hello there,

I installed django-blog-zinnia as recommended in the doc. I am using django-blog-zinnia==0.15.2 and Django==1.8.4. Here is the link to full traceback:
https://gist.github.com/sachitad/45da1ba8b0b95f8315e14236d9ba816d

**Comment by Fantomas42** [comment]
Hello, even if you are stuck with Django 1.8.x, I suggest you to install zinnia v0.16, because the incriminated part of code has been rewritten since the version 0.15.2

Regards
