### ISSUE TITLE
When running the tests, I am obtaining "There is 1 other session using the database" with Postgresql

### ISSUE THREAD

**Issue by jlariza** [Fantomas42/django-blog-zinnia#476]
Hello!

As the title says, almost everytime I run the tests I get

```
OperationalError: database "database_name" is being accessed by other users
DETAIL:  There is 1 other session using the database
```

I was not getting it until I start using django-blog-zinnia in my project.

Searching through internet, I found https://code.djangoproject.com/ticket/22420#comment:8

according to that comment, that person was also using django-blog-zinnia. Is there a chance that this error is produced by blog-zinnia?

Thank you!

**Comment by Fantomas42** [comment]
I think, this issue is coming from another application using "database_name". You should check the client connected to your database for having more informations.

But I don't think it's related to Zinnia itself...

**Comment by mick88** [comment]
I'm also getting this issue. It does not happen on master branch, only on the branch which adds zinnia.
In my case I'm using custom database name, which appends timestamp to allow me to run multiple test instances at the same time:

```python
DATABASES = {
    'default': {
        # ...
        'TEST': {
            'NAME': 'transplant_{}'.format(time.time()),
        }
    }
}
```

I used `SELECT * FROM pg_stat_activity;` to see databsae connections and noticed that when `DROP DATABASE` was being executed, there were still SQL queries running on zinnia: 
```SQL
SELECT "zinnia_category"."id", "zinnia_category"."title", "zinnia_category"."slug", "zinnia_category"."description", "zinnia_category"."parent_id", "zinnia_category"."lft", "zinnia_category"."rght", "zinnia_category"."tree_id", "zinnia_category"."level" FROM "zinnia_category" INNER JOIN "zinnia_entry_categories" ON ( "zinnia_category"."id" = "zinnia_entry_categories"."category_id" ) WHERE "zinnia_entry_categories"."entry_id" = 1 ORDER BY "zinnia_category"."tree_id" ASC, "zinnia_category"."lft" ASC
```
The above query hangs on while database is being dropped could it be caused by some work being done in another thread?

In my case it helps to run tests in reverse order with `./manage.py test -r`, which "fixes" the issue when running tests on my machine, but still randomly getting this problem on CI.

**Comment by mick88** [comment]
This appears to be caused by directory pingers, which run on a secondary thread. I fixed this by disabling them in my `settings.py`:
```python
# this fixes the issue
ZINNIA_SAVE_PING_DIRECTORIES = False
# This doesnt seem to make a difference for me, but I also disabled it for good measure
ZINNIA_PING_EXTERNAL_URLS = False
```

**Comment by jlariza** [comment]
@mick88 thank you, that solved the problem!

**Comment by Fantomas42** [comment]
Oh great ! Thanks for the solution.
I will implement a fix.

**Comment by Fantomas42** [comment]
Unfortunately I cannot reproduce the issue, and I does not help.
I was looking on the multi-threading implementation, but it seems to be disabled...

I don't know from where to start to fix it...

**Comment by Fantomas42** [comment]
Normally the pingers are triggered manually, not when a published entry is created, because the signals are disabled. But maybe I have missed something.

**Comment by fensterz** [comment]
I also ran into this problem and consistently received the same error until using the fix (ZINNIA_SAVE_PING_DIRECTORIES = False) suggested by @mick88 (thank you!)
Django==1.9.8
django-blog-zinnia==0.17
postgresql 9.5.3

**Comment by Fantomas42** [comment]
Hello,

in https://github.com/Fantomas42/django-blog-zinnia/commit/3c86754dbb65f99fbb88b60adf1e576467c0e3c1 the Thread functionality is totally disabled in the tests, the issue should not occurs anymore.

Regards
