### ISSUE TITLE
{% get_tags as entry_tags %} is broken in 0.17, with Django 1.8

### ISSUE THREAD

**Issue by dan-passaro** [Fantomas42/django-blog-zinnia#480]
In Django 1.8 with Zinnia 0.17, this `zinnia/base.html` template:

```
{% load zinnia %}
{% get_tags as entry_tags %}
```

seems to be causing this error:

```
TemplateSyntaxError: 'get_tags' received too many positional arguments
```

I have not tested with other versions of Django, but I have confirmed that this error does not occur with Zinnia 0.16.

**Comment by Fantomas42** [comment]
Yes, this is because of the compatibility with Django 1.9.
Stay in 0.16 if you are stuck with Django 1.8.
