### ISSUE TITLE
On admin side, Title override by other title doc

### ISSUE THREAD

**Issue by torxx666** [Fantomas42/django-blog-zinnia#481]
Hi, 
I get the following, let say I have doc1 (title1), doc2 (title2), doc3 (title3), I go to /admin/zinnia/entry/, I click on doc1, (/admin/zinnia/entry/1/change/ ), but I receive all data from doc2 !!!!!

**Comment by Fantomas42** [comment]
It's not a bug regarding Zinnia itself.
Certainly coming from your setup...
