### ISSUE TITLE
Backwards (in)compatibility and upgrading

### ISSUE THREAD

**Issue by bittner** [Fantomas42/django-blog-zinnia#483]
I've noticed while integrating Zinnia (and cmsplugin-zinnia) in a project that with every recent release there was at least one serious incompatibility introduced (see [the Zinnia docs](http://docs.django-blog-zinnia.com/en/develop/notes/compatibility.html)). I'm wondering what implications this has for upgrading in future.

When I have my users write blog posts today (Zinnia 1.6 on Django 1.8) can I be sure that upgrading to a future version of Zinnia in a few years will work?

**Comment by Fantomas42** [comment]
Currently the project in more or less in maintenance mode.
For each new releases of Django, a compatibility work is done for the latest version Django.

Actually your issue is coming from django-cms sticking you to Django 1.8.
If django-cms support more recent version of Django, Zinnia certainly will be compatible.

**Comment by bittner** [comment]
What is bothering me a bit is that a lot of projects, including Zinnia, are favoring the latest Django release over the LTS version 1.8. (I believe it's not always for the same reasons across all those projects, some may be technical necessities, I've not really done research and technical comparison.)

Personally, I'm fine with dropping support for Django < 1.8, mainly because 1.8 is LTS, (and Django < 1.7 should definitely be dropped for doing `syncdb` instead of `migrate` out-of-the-box). So, when I can choose, in my projects, I try to stay compatible with 1.8+.

What worries me about all the movement is, you're forced to follow along with every single minor release of Django. It feels a bit like the Django community goes havoc (I remember @jacobian's [2012 DjangoCon keynote](http://klewel.com/conferences/djangocon-2012/index.php?talkID=2) saying, _"Django is boring. And that is actually a good thing!"_ (23:33)). Chasing after the latest release should be unnecessary when having an LTS version, shouldn't it?

**Comment by Fantomas42** [comment]
About using LTS versions or latest versions, the problem is not related Zinnia, since I will always provide the old releases of Zinnia tight to a Django version.

But I agree, that chasing after the compatible releases can be a pain.
