### ISSUE TITLE
CHANGELOG was not updated or v0.18

### ISSUE THREAD

**Issue by bittner** [Fantomas42/django-blog-zinnia#485]
Just noticed that [version 0.18](https://pypi.python.org/pypi/django-blog-zinnia/0.18) of django-blog-zinnia was released 4 days ago, but the [CHANGELOG](https://github.com/Fantomas42/django-blog-zinnia/blob/develop/CHANGELOG) was obviously forgotten to update.

**Comment by Fantomas42** [comment]
Thanks for your vigilance !
