### ISSUE TITLE
Can't add or edit new entry in admin with version 0.18

### ISSUE THREAD

**Issue by zmrenwu** [Fantomas42/django-blog-zinnia#489]
I can't locate the bug accurately. But I think it lies in `EntryAdmin` since if I delete all codes of it, the issue fixed.
I also test it in version 0.17. There is no problem.
So I think it incured by some codes in  `EntryAdmin` of version 0.18.

The exception is:
```
TypeError at /admin/zinnia/entry/1/change/
render_options() takes 2 positional arguments but 3 were given
```

**Comment by Fantomas42** [comment]
Hello if you use the version 0.18, you should use the version 1.10 of Django.

Regards

**Comment by marianobrc** [comment]
I can't install django 1.10, I need Django 1.9, is any version of Zinnia working with Django 1.9?

**Comment by Fantomas42** [comment]
http://docs.django-blog-zinnia.com/en/develop/notes/compatibility.html

v0.17
