### ISSUE TITLE
Zinnia0.18, Django 1.9.4 - TypeError: render_options() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Tapo4ek** [Fantomas42/django-blog-zinnia#490]
When adding new entry got an error.

Comment 
```
    parent = TreeNodeChoiceField(
    label=_('Parent category'),
    empty_label=_('No parent category'),
    level_indicator='|--', required=False,
    queryset=Category.objects.all())
```
in `admin/forms.py` helps, but it is not write design.

**Comment by Fantomas42** [comment]
https://github.com/Fantomas42/django-blog-zinnia/issues/489

Please read the documentation or the closed issues, before opening a ticket.

**Comment by doctorpension** [comment]
Is there any way you could point me to the answer? I can't seem to find it by searching or in the docs.

**Comment by Fantomas42** [comment]
@doctorpension it's related to compatibility with Django
