### ISSUE TITLE
Blog post slug with the same name as template file renders the template file instead

### ISSUE THREAD

**Issue by satsurae** [Fantomas42/django-blog-zinnia#493]
# Actual behavior
When I was testing my zinnia install, I created a post called 'test'. When I wanted to view the post, it rendered a template file called 'test.html' instead, which was located in my templates folder but displayed the expected URL. I tried again, using a slug name called 'base' and it rendered base.html.

I also took the liberty of trying this on the zinnia live demo site with the slug 'base' and it again redirected me to 'base.html' from the zinnia project but showed the url as 'http://demo.django-blog-zinnia.com/blog/2016/12/05/base/' but there was no error message.

# Expected behavior
Even if the filename matches the slug, I was under the impression that the blog-post is identified with a combination of information (i.e. year, month, date) more than just the slug and so would always show the post even if there was a potential conflict.

# Steps to reproduce the issue

  1. Create blog post with a slug with the same name as a html file in your django project, e.g. 'test' --> 'test.html' in templates, 'base' --> 'base.html' in templates
  2. Open blog post called 'test', 'base' etc. and see the attempt to render 'test.hml' or 'base.html' in the blog post. 

# Specifications

 - Zinnia version: 0.17
 - Django version: 1.9
 - Python version: 3.5
 - Operating system: Mac OS X

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

here the list of template names generated with rendering an entry:

https://github.com/Fantomas42/django-blog-zinnia/blob/develop/zinnia/tests/test_mixins.py#L172

As you can see, it's in the latest case that the template is selected. I do not see this behavior as a bug, but more like a feature. :)

Having this kind of slug, is pretty rare and the issue would be easily identified.
I don't know what kind of fix to provide.

Regards
