### ISSUE TITLE
Allow for editing the number of random and recent entries that are shown

### ISSUE THREAD

**Issue by rowanv** [Fantomas42/django-blog-zinnia#497]
It would be useful to be able to edit the number of random and recent entries that are shown, so that they are not necessarily 5, but can be 3, 4, 6, etc. Depending on the custom layout that one has constructed, more or fewer entries can improve the site layout.

I've written up an initial attempt at being able to set the random and recent entries over at `https://github.com/rowanv/django-blog-zinnia/commit/3b9f63d8a727373216d4bb53cca481f35248f173`.

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [ x] I have read the guidelines for contributing linked to above.
 - [x ] I have checked for duplicate issues.
 - [ x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

thank you for your contribution, but I think that this option is not really useful,
because you can simply change how many items are displayed in the template.

http://docs.django-blog-zinnia.com/en/develop/ref/templatetags.html#get-recent-entries
