### ISSUE TITLE
Attribute error when EntryFeeds demanding for image size

### ISSUE THREAD

**Issue by FilippoIOVINE** [Fantomas42/django-blog-zinnia#499]
Hi,
Implementing a FileBrowser (basically a CharField) image field property to Entry model I got an AttributeError exception when feeds.

I guess you should amend adding this exception too:

```
class EntryFeed(ZinniaFeed):
...
    def item_enclosure_length(self, item):
        ...
        try:
            return str(item.image.size)
        except (os.error, NotImplementedError, AttributeError):
            pass
        ...
```
Thanks,
Filippo

 - Zinnia version: 0.18.1
 - Django version: 1.10.5
 - Python version: 2.7
 - Operating system: Mac osx

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

I have made a fix, but it's not really a good idea to override the default fields, even if it's the shortest way.

Regards

**Comment by FilippoIOVINE** [comment]
Thanks.
What would you suggest if I need to implement a FileBrowseField for images?

**Comment by Fantomas42** [comment]
To just add the field under another name, then adapt the needed classes like the feeds.

**Comment by FilippoIOVINE** [comment]
but reading from zinnia docs (http://docs.django-blog-zinnia.com/en/develop/how-to/extending_entry_model.html) I understood this was an accepted pattern: even applying for the example code you would encounter same error I reported above.

**Comment by Fantomas42** [comment]
Yes, it's an allowed pattern, but like shown in the doc, you have to adapt the admin, the templates, all the components touched by the modification.

I have forgotten the feeds, but with the fix provided, this issue should not happen anymore.
