### ISSUE TITLE
Excerpt is incorrect

### ISSUE THREAD

**Issue by chrismcb** [Fantomas42/django-blog-zinnia#503]
I noticed when I shared a blog post on Facebook, that the preview paragraph Facebook used was the wrong one.

It looks like the excerpt is set to be the first paragraph of the Content field.
I think it should be Lead paragraph (if it exists) otherwise it should be the first paragraph of the Content field.

**Comment by Fantomas42** [comment]
Hello,

this issue is more or less related to your templates.
I suggest you to change this behavior according to your needs in template zinnia/entry_detail.html.

Regards
