### ISSUE TITLE
Entry change error render_options() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by jaumemateu** [Fantomas42/django-blog-zinnia#505]
# Actual behavior
in admin =>  blog section => entries => select entry
In admin section when select entry to edit receive next error:
**render_options() takes exactly 2 arguments (3 given)**

# Expected behavior
in admin =>  blog section => entries => select entry => edit entry

# Steps to reproduce the issue

  1. login blog **http://localhost:8000/admin/**
  2. in blog section select entries **http://localhost:8000/admin/zinnia/entry/**
  3. select entry to edit **http://localhost:8000/admin/zinnia/entry/8/change**

# Specifications

 - Zinnia version: 0.18.1
 - Django version: 1.9
 - Python version: 2.7.12
 - Operating system: linux mint

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [X] I have read the guidelines for contributing linked to above.
 - [X] I have checked for duplicate issues.
 - [ ] This is not a support request.

# Proposed solution:

For django 1.9 I found that the problem is in zinnia/admin/widgets.py in the MPTTFilteredSelectMultiple, line number 49
def render_options(self, selected_choices):

in django/forms/widgets.py line 550:
def render_options(self, choices, selected_choices):

replace def render_options(self, selected_choices):
 with 
def render_options(self, choices=None, selected_choices=None):

**Comment by Fantomas42** [comment]
Hello,

http://docs.django-blog-zinnia.com/en/develop/notes/compatibility.html#compatibility-with-django

Either you use django 1.10 or you downgrade the version of Zinnia.

Regards

**Comment by jaumemateu** [comment]
Me apologies, I not read that section. 

The main reason whereby I downgraded the django version was because I had a problem with zinnia-wysiwyg-tinymce 1.4 as I explain in https://github.com/django-blog-zinnia/zinnia-wysiwyg-tinymce/issues/9

Kind Regards.
