### ISSUE TITLE
Tag with special character not found

### ISSUE THREAD

**Issue by iustitia** [Fantomas42/django-blog-zinnia#510]
# Actual behavior
When I add tag with special character ("bezpieczeństwo") to my entry, it can't find the webpage with this tag: https://programeria.pl/tags/bezpiecze%C5%84stwo/
Error log says: 
Not Found: /tags/bezpiecze%C5%84stwo/

However when I test it on my local environment, everything works as expected:
[19/May/2017 12:20:37] "GET /tags/bezpiecze%C5%84stwo/ HTTP/1.1" 200 20027

# Specifications

 - Zinnia version: 0.18.1
 - Django version: 1.10
 - Python version: 3.5.2
 - Operating system: FreeBSD

Any ideas what could be wrong with that? I was trying to investigate the issue, but I haven't found anything yet. This would be super useful for my site.

**Comment by Fantomas42** [comment]
Hello,

locally I have add this tag to an entry, and the url http://localhost:8000/blog/tags/bezpiecze%C5%84stwo/ works fine. 

This is certainly coming from your webserver.

Regards
