### ISSUE TITLE
Like a post functionality

### ISSUE THREAD

**Issue by harshmalik** [Fantomas42/django-blog-zinnia#516]
Is there like a post functionality available. If not, how can it be integrated?

# Specifications

 - Zinnia version:0.18
 - Django version:1.9
 - Python version:2.7
 - Operating system:ubuntu

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

do you mean 'like' a post àla facebook ?

Regards

**Comment by harshmalik** [comment]
Nope, Like a post for a anonymous User who visits the blog

**Comment by Fantomas42** [comment]
This kind of feature is not provided for security concerns, but you can implement this feature by your own  easily. Take a look at zinna.views.quick_entry.QuickEntry

Regards
