### ISSUE TITLE
TemplateDoesNotExist using theme

### ISSUE THREAD

**Issue by bradrice** [Fantomas42/django-blog-zinnia#517]
Whenever I try to use a custom theme like zinnia-theme-foundation I get this error:

Exception Type: | TemplateDoesNotExist
-- | --
zinnia:zinnia/entry_archive.html
 And going to the line in the file is:

{% extends "zinnia:zinnia/entry_archive.html" %}
--
It appears to have something to do with the zinnia:zinnia in the extends. My template paths have this:

/home/bradrice/webapps/bradweb/web/templates/zinnia:zinnia/entry_archive.html (Source does not exist)
home/bradrice/lib/python3.4/zinnia_foundation/templates/zinnia:zinnia/entry_archive.html (Source does not exist)
etc. 

I can find the template if I leave off the zinnia:zinnia and just change it to zinnia.

I'm quite sure I must have something mis-configured, but I'm at a loss as to what is wrong and how I fix it. Could you help?

**Comment by vinayk3** [comment]
add loaders inside templates, below is the code snippet
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 'APP_DIRS': True, /*comment this line*/
        'OPTIONS': {

        'loaders': [
               'app_namespace.Loader',
               'django.template.loaders.filesystem.Loader',
               'django.template.loaders.app_directories.Loader',
               'django.template.loaders.eggs.Loader',
            ],
            
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'zinnia.context_processors.version',  # Optional
            ],
        },
    },
]
