### ISSUE TITLE
No issue guidelines linked

### ISSUE THREAD

**Issue by benjaoming** [Fantomas42/django-blog-zinnia#523]
Sorry I'm not filling in the blanks :)

The following appears in the issue template:

```
 - [ ] I have read the guidelines for contributing linked to above.
```

However, there are no guidelines because there is no SUPPORT.rst. If you want one, consider this:

https://github.com/django-wiki/django-wiki/blob/master/SUPPORT.rst

**Comment by Fantomas42** [comment]
Hello,

some time ago, github displayed a link on contribution guidelines if a certain file was present.

It's seems to don't be the case any longer.

I will investigate, thanks for the report.

Regards

**Comment by benjaoming** [comment]
One is now for PRs and the other is for issues I think... you might have to move `CONTRIBUTING.md` into the root of the repo

**Comment by Fantomas42** [comment]
The message is now displayed on issue and PR list. I will adapt the templates.

**Comment by benjaoming** [comment]
I thought this was an issue in this repo, but I see now that it's an issue across all repos. Have asked Github tech support what's going on since I couldn't find any information about it.

**Comment by benjaoming** [comment]
I got a kind and quick response from GH -- unfortunately, though, it seems like they want the more discreet version for now -- but hopefully they'll change their minds :)

> Hi Ben,
> 
> Thanks for writing in about this! It's not ignored, but we updated the visuals and now only show it to your repository's first-time contributors on the main issues page. You can look at a repo you've never contributed to before to try it out:
> 
> https://github.com/rails/rails/issues
> 
> There's more work coming in this area soon, so if you have any feedback about that, please let me know and I'll pass it on to the team 
> 
> All the best,
> Rachel

Also lulz... props to Rachel for picking Rails as a certain first-time contributor link for me :D
