### ISSUE TITLE
After I customize entry model.Tinymce not work

### ISSUE THREAD

**Issue by timchou** [Fantomas42/django-blog-zinnia#524]
Hello

custom zinnia entry model
`
class EntryBestBuy(AbstractEntry):
    products = models.ManyToManyField('mall.ProductSet',blank=True)

    def __str__(self):
        return 'EntryBestBuy %s' % self.title

    class Meta(AbstractEntry.Meta):
        abstract = True
`

custom zinnia admin.py
`class EntryBestBuyAdmin(EntryAdmin):
    fieldsets = EntryAdmin.fieldsets + ( ('Products', {'fields': ('products',)}) ,)
    filter_horizontal = ('products',)
admin.site.register(Entry, EntryBestBuyAdmin)
`

setting.py:
`
ZINNIA_URL_SHORTENER_BACKEND = 'www.backend'
ZINNIA_ENTRY_BASE_MODEL = 'zinnia_extra.models.EntryBestBuy'
`

django-blog-zinnia==0.18.1
zinnia-wysiwyg-tinymce==1.4
django-tinymce==2.2.0

After I customize entry model like this, Tinymce in admin not work any more.If I remove 
`ZINNIA_ENTRY_BASE_MODEL = 'zinnia_extra.models.EntryBestBuy'`
in settings.py .Tinymce work again.

**Comment by Fantomas42** [comment]
Hello,

the issue is coming from here https://github.com/django-blog-zinnia/zinnia-wysiwyg-tinymce/blob/develop/zinnia_tinymce/admin.py#L41

You have to register manually like in the provided example your admin class.

Regards

**Comment by timchou** [comment]
wow  ,thanks a lot!
