### ISSUE TITLE
How to change the font size of every article displayed in the blog？

### ISSUE THREAD

**Issue by 5267** [Fantomas42/django-blog-zinnia#526]
![image](https://user-images.githubusercontent.com/19160836/32412473-c839c1e4-c233-11e7-82e9-ee361817cf85.png)
如上图，正文部分文章字体太大，我想调小一点，不过，找了半天，没找到是哪个文件在控制文章的字体大小，求指点一下，万分感谢！

**Comment by Fantomas42** [comment]
CSS ?

**Comment by 5267** [comment]
请问博客正文的文字大小对应的CSS文件是哪一个呢？ 真心找 了好久都没找到啊，求指导

**Comment by Fantomas42** [comment]
Add your own CSS file in the templates of the blog.
