### ISSUE TITLE
python 3 report  strange  error

### ISSUE THREAD

**Issue by jackiilong** [Fantomas42/django-blog-zinnia#528]
python 3 
cd doc;
make html

Running Sphinx v1.6.5
Register XML-RPC methods from settings.XMLRPC_METHODS
Registering 'zinnia.xmlrpc.pingback:pingback_ping' => 'pingback.ping'
Registering 'zinnia.xmlrpc.pingback:pingback_extensions_get_pingbacks' => 'pingback.extensions.getPingbacks'
Registering 'zinnia.xmlrpc.metaweblog:get_users_blogs' => 'blogger.getUsersBlogs'
Registering 'zinnia.xmlrpc.metaweblog:get_user_info' => 'blogger.getUserInfo'
Registering 'zinnia.xmlrpc.metaweblog:delete_post' => 'blogger.deletePost'
Registering 'zinnia.xmlrpc.metaweblog:get_authors' => 'wp.getAuthors'
Registering 'zinnia.xmlrpc.metaweblog:get_tags' => 'wp.getTags'
Registering 'zinnia.xmlrpc.metaweblog:get_categories' => 'metaWeblog.getCategories'
Registering 'zinnia.xmlrpc.metaweblog:new_category' => 'wp.newCategory'
Registering 'zinnia.xmlrpc.metaweblog:get_recent_posts' => 'metaWeblog.getRecentPosts'
Registering 'zinnia.xmlrpc.metaweblog:get_post' => 'metaWeblog.getPost'
Registering 'zinnia.xmlrpc.metaweblog:new_post' => 'metaWeblog.newPost'
Registering 'zinnia.xmlrpc.metaweblog:edit_post' => 'metaWeblog.editPost'
Registering 'zinnia.xmlrpc.metaweblog:new_media_object' => 'metaWeblog.newMediaObject'

Extension error:
Could not import extension extensions.zinnia_docs (exception: cannot import name 'force_unicode')
Makefile:40: recipe for target 'html' failed
make: *** [html] Error 1

But this is not present if I use python 2.

**Comment by Fantomas42** [comment]
Thanks for the report !
