### ISSUE TITLE
Markdown code output does not recognize new lines correctly

### ISSUE THREAD

**Issue by smileservices** [Fantomas42/django-blog-zinnia#542]
# Actual behavior
```
sudo -H pip3 install --upgrade pip 
sudo -H pip3 install virtualenv 
```
Are put together into one single line of code block

# Expected behavior
should remain two lines when parsed into code block

# Steps to reproduce the issue
  1. Set ZINNIA_MARKUP_LANGUAGE to 'markdown'
  2. Write some code in markdown language:
```
sudo -H pip3 install --upgrade pip
sudo -H pip3 install virtualenv
```
  3. Open post

# Specifications

 - Zinnia version: 0.20
 - Django version: 1.11
 - Python version: 3.52
 - Operating system: Windows/Ubuntu

# Disclaimer

Before submitting an *issue* make sure you have:

 - [x] Read the guidelines for contributing.
 - [x] Checked for duplicate issues.
 - [x] Not a support request.

**Comment by peterdoherty01** [comment]
Did you install markdown via pip? 

I got it working by the following implementation as per the docs:

1. ZINNIA_MARKUP_LANGUAGE = 'markdown' in the settings file
2. pip install markdown
