### ISSUE TITLE
For people who wants to use tinymce4 instead of the tinymce3

### ISSUE THREAD

**Issue by gohanko** [Fantomas42/django-blog-zinnia#543]
I created a small package that take care of this for you.
https://github.com/ojiii/django-zinnia-tinymce4

**Comment by milossh** [comment]
@ojiii You removed it?

**Comment by gohanko** [comment]
@milossh Yeah, I did. I was cleaning up my repositories and it seems too simple to be a package worthy so I removed it. It basically used django-tinymce4-lite and applying tinymce4 on the field.

**Comment by gohanko** [comment]
I should also remove this
