### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by LorhanSohaky** [Fantomas42/django-blog-zinnia#558]
# Actual behavior
![image](https://user-images.githubusercontent.com/16273730/63561998-582ea780-c532-11e9-8f7a-f6ba3a7f9e2e.png)

# Steps to reproduce the issue

  1. Access http://docs.django-blog-zinnia.com/

**Comment by hvrmeer** [comment]
Actual behaviour indeed. 😬

**Comment by FPierreAE** [comment]
Any ETA on documentation fix?

**Comment by LorhanSohaky** [comment]
Nope

**Comment by randomnoob** [comment]
Here you go, directly from readthedocs
https://django-blog-zinnia.readthedocs.io/en/latest/index.html

**Comment by Fantomas42** [comment]
DNS configuration updated !
Now works again
